name: medios_continuos
channels:
  - conda-forge
  - defaults
dependencies:
  # Paquetes básicos
  - python>3.6
  - numpy
  - scipy
  - matplotlib
  - sympy
  - jupyter
  # Paquetes para visualización
#  - vtk
#  - pyvista==0.23.1
  - mayavi
  - pyqt
  - ipywidgets
  - itkwidgets
  - panel
  - pip
  - pip:
    - meshio==3.0
    - solidspy==1.0.16
